name: CI

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: test
        run: flutter test